feat(typescript): add TypeScript examples
appcelerator/titanium-boilerplates pull request #1
Opened 2018-08-03 13:11 UTC by janvennemann

**WIP**

The examples still need some love as they currently are only the default app templates that don't make much use of TypeScript features.

2018-08-06 20:57 UTC, janvennemann commented
@hansemannn I'll add tslint tomorrow and then this should be ready ;)

2018-08-07 05:52 UTC, hansemannn requested changes
Only one quick note. Works reaally nice and fast!

2018-08-07 05:52 UTC, hansemannn commented on templates/typescript-alloy-app/.gitignore
> +plugins/ti.alloy
We should not put that on .gitignore as it's causing a build failure when missing this file. It should reaaaally not love in the every project anyway, but until thats fixed, let's restore the dir and remove it from here (ryming like boss).

2018-08-07 05:56 UTC, hansemannn commented
Oh, also, you should let them know to run `npm i` before using the setup. I just ran into that whe n testing classic (which also works fine afterwards)!

2018-08-07 12:41 UTC, hansemannn approved these changes
Looks **awesome**!

2018-08-07 12:47 UTC, merged